(ns web.rtc.core
  "web.rtc interfaces."
  (:require [web.rtc.ConstrainDouble]
            [web.rtc.LocalMediaStream]
            [web.rtc.MediaStreamEvent]
            [web.rtc.RTCCertificate]
            [web.rtc.RTCConfiguration]
            [web.rtc.RTCDTMFToneChangeEvent]
            [web.rtc.RTCDataChannel]
            [web.rtc.RTCDataChannelEvent]
            [web.rtc.RTCDtlsTransport]
            [web.rtc.RTCIceCandidate]
            [web.rtc.RTCIceCandidateInit]
            [web.rtc.RTCIceCandidatePair]
            [web.rtc.RTCIceCandidatePairStats]
            [web.rtc.RTCIceCandidateStats]
            [web.rtc.RTCIceParameters]
            [web.rtc.RTCIceServer]
            [web.rtc.RTCIdentityAssertion]
            [web.rtc.RTCIdentityErrorEvent]
            [web.rtc.RTCIdentityEvent]
            [web.rtc.RTCInboundRtpStreamStats]
            [web.rtc.RTCOfferAnswerOptions]
            [web.rtc.RTCOfferOptions]
            [web.rtc.RTCOutboundRtpStreamStats]
            [web.rtc.RTCPeerConnectionIceEvent]
            [web.rtc.RTCRtpCodecParameters]
            [web.rtc.RTCRtpContributingSource]
            [web.rtc.RTCRtpEncodingParameters]
            [web.rtc.RTCRtpReceiver]
            [web.rtc.RTCRtpStreamStats]
            [web.rtc.RTCRtpSynchronizationSource]
            [web.rtc.RTCRtpTransceiver]
            [web.rtc.RTCRtpTransceiverInit]
            [web.rtc.RTCSctpTransport]
            [web.rtc.RTCStats]
            [web.rtc.RTCTrackEvent]
            [web.rtc.RTCTrackEventInit]))
