(ns web.workers.core
  "web.workers interfaces."
  (:require [web.workers.AbstractWorker]
            [web.workers.Clients]
            [web.workers.DedicatedWorkerGlobalScope]
            [web.workers.DedicatedWorkerGlobalScope.ev]
            [web.workers.ErrorEvent]
            [web.workers.ExtendableEvent]
            [web.workers.FetchEvent]
            [web.workers.InstallEvent]
            [web.workers.MessageEvent]
            [web.workers.NavigatorConcurrentHardware]
            [web.workers.PushEvent]
            [web.workers.ServiceWorker]
            [web.workers.ServiceWorkerContainer]
            [web.workers.ServiceWorkerContainer.ev]
            [web.workers.ServiceWorkerGlobalScope]
            [web.workers.ServiceWorkerGlobalScope.ev]
            [web.workers.ServiceWorkerRegistration]
            [web.workers.SharedWorker]
            [web.workers.SharedWorkerGlobalScope]
            [web.workers.SharedWorkerGlobalScope.ev]
            [web.workers.SyncEvent]
            [web.workers.Worker]
            [web.workers.Worker.ev]
            [web.workers.WorkerGlobalScope]
            [web.workers.WorkerGlobalScope.ev]
            [web.workers.WorkerLocation]
            [web.workers.WorkerNavigator]))
