(ns web.css.core
  "web.css interfaces."
  (:require [web.css.CSSCounterStyleRule]
            [web.css.CSSKeywordValue]
            [web.css.CSSMathSum]
            [web.css.CSSMathValue]
            [web.css.CSSNumericValue]
            [web.css.CSSPositionValue]
            [web.css.CSSPrimitiveValue]
            [web.css.CSSPseudoElement]
            [web.css.CSSStyleValue]
            [web.css.CSSUnitValue]
            [web.css.CSSUnparsedValue]
            [web.css.CSSValue]
            [web.css.CSSValueList]
            [web.css.CSSVariableReferenceValue]
            [web.css.PaintWorklet]
            [web.css.Point]
            [web.css.StylePropertyMap]
            [web.css.StylePropertyMapReadOnly]))
